---
- hosts: 'lb'
  tasks:
          - name: "installing haproxy"
            package:
                    name: "haproxy"
                    state: present
          
          - name: "updating ha file"
            template:
                    src: "/root/yum/haproxy/haproxy.cfg"
                    dest: "/etc/haproxy/haproxy.cfg"
          - name: "Starting haproxy"
            service:
                    name: "haproxy"
                    state: restarted

